// seed.js
const mongoose = require('mongoose');
require('dotenv').config();

const Book = require('./models/book');

const books = [
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    description: 'A novel about injustice in the deep South.',
    eVersionLink: 'https://online.fliphtml5.com/pevm/qank/#p=8',
    image: 'http://localhost:5000/uploads/tokillamockingbird.jpeg',
    category: 'Fiction',
    available: true,
    borrowedBy: null,
  },
  {
    title: '1984',
    author: 'George Orwell',
    description: 'Dystopian novel about totalitarian regime.',
    eVersionLink: 'https://www.george-orwell.org/1984/0.html',
    image: 'http://localhost:5000/uploads/1984.jpeg',
    category: 'Dystopian',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'A critique of the American Dream.',
    eVersionLink: 'https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf',
    image: 'http://localhost:5000/uploads/TheGreatGatsby.jpeg',
    category: 'Classic',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'A romantic novel of manners.',
    eVersionLink: 'https://giove.isti.cnr.it/demo/eread/Libri/joy/Pride.pdf',
    image: 'http://localhost:5000/uploads/PrideandPrejudice.jpeg',
    category: 'Romance',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'Fantasy adventure of Bilbo Baggins.',
    eVersionLink: 'https://primarysite-prod-sorted.s3.amazonaws.com/gobowen-primary-school/UploadedDocument/db3a2424ab834ade94f16606d5567712/the-hobbit-1.pdf',
    image: 'http://localhost:5000/uploads/THehobbit.jpeg',
    category: 'Fantasy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    description: 'A boy discovers he is a wizard.',
    eVersionLink: 'https://pwc.res.zabanshenas.ir/Harry_Potter_and_the_Sorcerer_s_Stone_www_libpdf_blog_ir_aba92c0a66.pdf',
    image: 'http://localhost:5000/uploads/Harrypotter.jpeg',
    category: 'Fantasy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    description: 'Teenage rebellion and alienation.',
    eVersionLink: 'https://giove.isti.cnr.it/demo/eread/Libri/sad/Rye.pdf',
    image: 'http://localhost:5000/uploads/theCatcher.jpeg',
    category: 'Fiction',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    description: 'A quest for revenge against a giant whale.',
    eVersionLink: 'https://uberty.org/wp-content/uploads/2015/12/herman-melville-moby-dick.pdf',
    image: 'http://localhost:5000/uploads/Moby-Dick.jpeg',
    category: 'Adventure',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    description: 'A woman’s journey to independence.',
    eVersionLink: 'https://www.ucm.es/data/cont/docs/119-2014-04-09-Jane%20Eyre.pdf',
    image: 'http://localhost:5000/uploads/JaneEyre.jpeg',
    category: 'Romance',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'A journey of self-discovery.',
    eVersionLink: 'https://icrrd.com/public/media/15-05-2021-084550The-Alchemist-Paulo-Coelho.pdf',
    image: 'http://localhost:5000/uploads/The Alchemist.jpeg',
    category: 'Philosophy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Book Thief',
    author: 'Markus Zusak',
    description: 'A story set in Nazi Germany told by Death.',
    eVersionLink: 'https://cdnsm5-ss3.sharpschool.com/UserFiles/Servers/Server_4204286/Image/Grade9GT--TheBookThiefMarkusZusak.pdf',
    image: 'http://localhost:5000/uploads/The Book Thief.jpeg',
    category: 'Historical Fiction',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    description: 'Epic fantasy of good versus evil.',
    eVersionLink: 'https://gosafir.com/mag/wp-content/uploads/2019/12/Tolkien-J.-The-lord-of-the-rings-HarperCollins-ebooks-2010.pdf',
    image: 'http://localhost:5000/uploads/The Lord of the Rings.jpeg',
    category: 'Fantasy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Animal Farm',
    author: 'George Orwell',
    description: 'Political allegory in a barnyard setting.',
    eVersionLink: 'https://www.arvindguptatoys.com/arvindgupta/orwellanimalfarm.pdf',
    image: 'http://localhost:5000/uploads/animalfarm.jpeg',
    category: 'Satire',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    description: 'A future controlled by technology and drugs.',
    eVersionLink: 'https://www.plato-philosophy.org/wp-content/uploads/2016/05/BraveNewWorld-1.pdf',
    image: 'http://localhost:5000/uploads/Brave New World.jpeg',
    category: 'Dystopian',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    description: 'A dark tale of love and revenge.',
    eVersionLink: 'https://www.ucm.es/data/cont/docs/119-2014-04-09-Wuthering%20Height',
    image: 'http://localhost:5000/uploads/Wuthering Heights.jpeg',
    category: 'Classic',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    description: 'Children find a magical land through a wardrobe.',
    eVersionLink: 'https://s3.amazonaws.com/scschoolfiles/112/thechroniclesofnarnia.pdf',
    image: 'http://localhost:5000/uploads/The Chronicles of Narnia.jpeg',
    category: 'Fantasy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    description: 'A moving story of friendship and redemption.',
    eVersionLink: 'https://mrsmeganparrish.weebly.com/uploads/3/8/0/5/38056115/the_kite_runner.pdf',
    image: 'http://localhost:5000/uploads/The Kite Runner.jpeg',
    category: 'Drama',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    description: 'A brief history of humankind.',
    eVersionLink: 'https://staibabussalamsula.ac.id/wp-content/uploads/2023/11/yuval_noah_harari-sapiens_a_brief_histor.pdf',
    image: 'http://localhost:5000/uploads/Sapiens.jpeg',
    category: 'Non-fiction',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    description: 'Political and magical struggles in Westeros.',
    eVersionLink: 'https://www.nothuman.net/images/files/discussion/1/e72f9f1f181a66887baa7270037c582e',
    image: 'http://localhost:5000/uploads/Game of thrones.jpeg',
    category: 'Fantasy',
    available: true,
    borrowedBy: null,
  },
  {
    title: 'The Fault in Our Stars',
    author: 'John Green',
    description: 'A love story of two cancer-stricken teenagers.',
    eVersionLink: 'https://spensabayalibrary.wordpress.com/wp-content/uploads/2016/04/the-fault-in-our-stars.pdf',
    image: 'http://localhost:5000/uploads/he Fault in Our Stars.jpeg',
    category: 'Romance',
    available: true,
    borrowedBy: null,
  },
];

mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('MongoDB connected');
    await Book.deleteMany({});
    await Book.insertMany(books);
    console.log('Database seeded successfully!');
    mongoose.disconnect();
  })
  .catch(err => {
    console.error('Error seeding database:', err);
  });
